10 criar documentacao uso api
Alohomora-team/2019.2-AlohomoraPage pull request #2
Opened 2019-11-06 02:40 UTC by VictorJorgeFGA

# Issue #10

 Resolve #10 - Criar documentação de uso da API

## Modificações

- [ ] Cobertura das querys e mutations bem como detalhes de uso no documento de uso

2019-11-06 12:27 UTC, mateusnr requested changes
O documento no geral está muito bom, gostei bastante.

Duas coisas que eu acharia interessante colocar no documento também seriam:
- Caso o usuário tenha a credencial de administrador, como ele poderá mandar as requisições que ele deseja como admin?
- Criar um tópico de exemplos e incluir um exemplo que faça uso do vetor MFCC

2019-11-06 12:27 UTC, mateusnr commented on docs/uso/guia_de_uso.md
> +> ***mfccAudioSpeakingName***: o vetor de características [MFCC](https://en.wikipedia.org/wiki/Mel-frequency_cepstrum) do áudio do morador dizendo o próprio nome
Nessa parte seria melhor colocar quebras de linha para facilitar a leitura

2019-11-06 12:27 UTC, mateusnr commented on docs/uso/guia_de_uso.md
> +
Apesar de estar mostrando normalmente no Github, no mkdocs a formatação desse trecho não está saindo como esperado

2019-11-06 12:27 UTC, mateusnr commented on docs/uso/guia_de_uso.md
> +*Alguma dúvida? Confira os [exemplos](#exemplos)*!
Não existe essa seção no documento, há outras ocorrências dessa linha no documento também

2019-11-06 12:27 UTC, mateusnr commented on docs/uso/guia_de_uso.md
> +> ***cpf***: o cpf do visitante
Mesma coisa citada anteriormente, adicionar quebras de linha na hora de descrever os campos

2019-11-06 12:27 UTC, mateusnr commented on docs/uso/guia_de_uso.md
> +> ***password***: a senha do funcionário ou da empresa
Quebra de linha

2019-11-06 12:27 UTC, mateusnr commented on docs/uso/guia_de_uso.md
> +> ***voiceData***: O vetor de áudio, em formato JSON, do morador dizendo a frase comum
Quebra de linha.

Sugestão: sobre o `voiceData`, seria legal ter algum exemplo de como é na prática uma query com esse atributo e/ou documentar o formato esperado

2019-11-06 12:27 UTC, mateusnr commented on docs/uso/guia_de_uso.md
> +> .
Que credenciais são essas?

2019-11-06 18:54 UTC, VictorJorgeFGA commented on docs/uso/guia_de_uso.md
> +> .
Essa parte aqui vai ficar pendente por enquanto. Pelo menos até definirmos qual vai ser a conta de admin padrão da API

2019-11-06 19:07 UTC, mateusnr commented on docs/uso/guia_de_uso.md
> +> .
Ok

2019-11-07 00:45 UTC, mateusnr commented on docs/uso/guia_de_uso.md
> +## Conteúdo
Esse tipo de linkagem com 3 traços `---` não está funcionando no mkdocs, se não me engano se usar um traço só funciona

2019-11-07 00:47 UTC, mateusnr commented on docs/uso/guia_de_uso.md
> +        - 2.1.3 - [Modificando os dados de um morador](#213---modificando-os-dados-de-um-morador)
*Vale pra todas as linkagens feitas em seções do documento*

Esses três traços `---`, apesar de ele linkar normal no viewer de markdown do Github, no mkdocs ele não consegue acessar, mas com um traço só `-` imagino que funcione

2019-11-07 01:23 UTC, mateusnr commented
Depois de terminar, coloca o guia de uso dentro da pasta projeto e coloca uma entrada da página no `mkdocs.yml`

2019-11-07 01:38 UTC, VictorJorgeFGA commented on docs/uso/guia_de_uso.md
> +        - 2.1.3 - [Modificando os dados de um morador](#213---modificando-os-dados-de-um-morador)
No github o traço único não parece funcionar. Mas há uma maneira de contornar isso.

2019-11-07 01:42 UTC, VictorJorgeFGA commented
Vou acabar nerfando algumas coisas por enquanto. Por incompetência minha, ainda me restam 21 horas de issues pra realizar essa semana. Depois volto a dar atenção a esse documento. Pedi para o @higton dar uma mão na parte de exemplificar como se comunicar como administrador.

2019-11-08 01:21 UTC, mateusnr commented on docs/projeto/guia_de_uso.md
> +> Disponível apenas para **[administrador](#5---administração)**
Alguns links dentro do documento ainda estão com os três traços

2019-11-08 01:24 UTC, mateusnr commented on docs/projeto/guia_de_uso.md
> +Com o token recebido apartir desta mutation deve ser copiado para o header, para fazer isso pode ser utilizado um programa chamado insomnia. Depois de feito essa etapa, já vai ser possível realizar t
Imagino que você quis dizer que: com o token que foi recebido você deve passá-lo no header de uma requisição que o usuário irá fazer. 

> para fazer isso pode ser utilizado um programa chamado insomnia.

Acredito que aqui qualquer client REST se aplique

2019-11-08 12:04 UTC, higton commented on docs/projeto/guia_de_uso.md
> +Com o token recebido apartir desta mutation deve ser copiado para o header, para fazer isso pode ser utilizado um programa chamado insomnia. Depois de feito essa etapa, já vai ser possível realizar t
só citei um exemplo

2019-11-08 18:55 UTC, VictorJorgeFGA commented on docs/projeto/guia_de_uso.md
> +> Disponível apenas para **[administrador](#5---administração)**
Corrigido

2019-11-08 23:11 UTC, mateusnr approved these changes
Se for necessário arrumar mais coisas posteriormente, abrirei outra issue, por agora já tem bastante coisa e já dá pra subir.

2019-11-08 23:50 UTC, merged